### ISSUE TITLE
strapi-plugin-webpage-builder is not working

### ISSUE THREAD

**Issue by loan9202** [uwizy/strapi-plugin-webpage-builder#3]
Hi Admin,
I apply strapi-plugin-webpage-builder flowing step: 
1. yarn add strapi-plugin-webpage-builder
2. create admin/admin.config.js with content:
```
module.exports = {
  webpack: (config, webpack) => {
    // Note: we provide webpack above so you should not `require` it
    // Perform customizations to webpack config
    // Important: return the modified config
 
    // Allow scss modules
    config.resolve = { ...config.resolve, extensions: [...config.resolve.extensions, '.scss'] };
 
    // Configure a SASS loader
    config.module.rules.push({
      test: /\.s[ac]ss$/i,
      use: [
        'style-loader',
        'css-loader',
        'sass-loader',
        {
          loader: 'sass-loader',
          options: {
            implementation: require('sass'),
          },
        },
      ],
    });
 
    return config;
  },
};

```
3. Create Blog collection type:

> title : Text
> content: json
> status: boolean

and I edit Blog controler:
```

'use strict';
const { sanitizeEntity } = require('strapi-utils');
 
const cleanupEntity = (entity) => {
  const { content } = entity;
 
  return { ...entity, content: { html: content.html, css: content.css } };
};
 
module.exports = {
  async find(ctx) {
    let entities;
    if (ctx.query._q) {
      entities = await strapi.services.yourModel.search(ctx.query); /* eslint-disable-line no-undef */
    } else {
      entities = await strapi.services.yourModel.find(ctx.query); /* eslint-disable-line no-undef */
    }
 
    return entities.map((entity) => {
      return sanitizeEntity(cleanupEntity(entity), { model: strapi.models.yourModel } /* eslint-disable-line no-undef */);
    });
  },
  async findOne(ctx) {
    const { id } = ctx.params;
 
    const entity = await strapi.services.yourModel.findOne({ id }); /* eslint-disable-line no-undef */
 
    return sanitizeEntity(cleanupEntity(entity), { model: strapi.models.yourModel } /* eslint-disable-line no-undef */);
  },
};

```
When I add data in blog, i didn't see GrapesJS view in field content. Could you help me find what i'm wrong ?

**Comment by loan9202** [comment]
I fixed this problem

**Comment by shlaing** [comment]
@loan9202 , How did you fix? It didn't appeared

**Comment by vukhacbiet** [comment]
@loan9202 The same question, how did you fix it

**Comment by arin-pang** [comment]
@shlaing , @vukhacbiet 

1. [Import SASS](https://github.com/Ulibka68/strapi-scss-sass-webpack) to your project.  `yarn add sass-loader@10.1.1 sass@1.32.8 --dev`
2. After import SASS, add **admin/admin.config.js** file to your project. and build the project. `yarn build`
3. launch your project with develop mode. `yarn develop`
3. Create new content-type in Content-type builder. It must implemented JSON attribute which named 'content'.
4. Change **your-project/api/_content-type-name_/controllers/_content-type-name_.js**
5. Now, you may see GrapesJS at new data page!

**Comment by jspizziri** [comment]
@uwizy I'd recommend adding the above to the docs.

**Comment by mfreeman-xtivia** [comment]
So a couple of things are still a mystery to me even after following this recipe:

1--does this only work to edit existing page content created using the backend Admin Api, or can i create new pages using GrapesJS?


2--What does "...see GrapesJS at new data page?" from the comment by @loan9202 actually mean?
